### ISSUE TITLE
Cursor highlighter not centered around cursor

### ISSUE THREAD

**Issue by hp3721** [iDarkLightning/portfolio-astro#1]
The cursor highlighter is no longer centered around the cursor after clicking. A suggested fix is setting the cursor highlighter's transform back to `translateX(-50%) translateY(-50%)` rather than `scale(1)`.
https://github.com/iDarkLightning/portfolio-astro/blob/b0f3833cc713a9f8f23f4d9bc1e0985bea1f9e81/src/components/cursor.astro#L10
https://github.com/iDarkLightning/portfolio-astro/blob/b0f3833cc713a9f8f23f4d9bc1e0985bea1f9e81/src/components/cursor.astro#L34

**Comment by iDarkLightning** [comment]
No longer applicable in latest version
